#!/bin/bash

set -x

export PATH=/snap/bin:$PATH

mkdir -p "$CHARM_BUILD_DIR/$CHARM"
CHARM_PATH="$(realpath "charms/$CHARM")"
(cd "$CHARM_BUILD_DIR" && charmcraft build -f "$CHARM_PATH")
unzip -q "$CHARM_BUILD_DIR/$CHARM.charm" -d "$CHARM_BUILD_DIR/$CHARM"
