#!/bin/bash

echo "Verifying dependencies"
if ! which pipenv > /dev/null; then
    echo "Installing pipenv..."
    sudo pip3 install pipenv
fi

(cd charms/metallb-controller && pipenv update)
(cd charms/metallb-speaker && pipenv update)
