#!/bin/bash

set -x

export PATH=/snap/bin:$PATH

charm whoami
RET=$?
if ((RET > 0)); then
    echo "Not logged into charm store"
    exit 1
fi

URL=$(charm push . cs:~"$NAMESPACE"/"$CHARM" | yq r - url)
IMAGE_NAME="$CHARM-image"
IMAGE=$(yq r "charms/$CHARM/metadata.yaml" "resources.$IMAGE_NAME.upstream-source")
docker pull "$IMAGE"
IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$IMAGE_NAME=$IMAGE" | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')

if [ "$CHANNEL" != unpublished ]; then
   charm release "$URL" --channel "$CHANNEL" --resource "$IMAGE_NAME"-"$IMAGE_REV"
fi
